services:
  eureka-naming-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    container_name: eureka-naming-server
    networks:
      - global-network

networks:
  global-network:
    name: global-network
    external: true
    driver: bridge
