spring:
  application:
    name: eureka-naming-server

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-naming-server-service
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/