apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-naming-server-deployment
  namespace: hah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-naming-server
  template:
    metadata:
      labels:
        app: eureka-naming-server
    spec:
      automountServiceAccountToken: false
      containers:
        - name: eureka-naming-server-container
          image: europe-west3-docker.pkg.dev/gd-gcp-internship-dc/hah-registry/eureka-naming-server:initial
          ports:
            - containerPort: 8761
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
              ephemeral-storage: "256Mi"
            limits:
              memory: "1Gi"